version: '3'

services:
    es:
      image: "cobrijani/elusive:latest_es"
      #build: "elasticsearch"
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - "elk"
      volumes:
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    kibana:
      image: "cobrijani/elusive:latest_kibana"
      #build: "kibana"
      ports:
        - "5601:5601"
      networks:
        - "elk"
      volumes:
        - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
    logstash:
      image: "cobrijani/elusive:latest_logstash"
      #build: "logstash"
      ports:
        - "5044:5044"
      networks:
        - "elk"
      volumes:
        - ./logstash/logstash.yml:/opt/logstash/config/logstash.yml
        - ./logstash/pipeline/:/etc/logstash/conf.d/
        - ./logstash/patterns/:/opt/logstash/patterns/
    apachebeat:
      build: "filebeat"
      networks:
        - elk
      volumes:
        - ./../test_logs/apache/:/var/log/apache
      environment:
        - BEAT_NAME=apache-beat
        - INDEX_NAME=apachebeat
    firebeat:
      build: "filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/firewall/:/var/log/firewall
      environment:
       - BEAT_NAME=fire-beat
       - INDEX_NAME=firebeat
    appbeat:
      build: "filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/application/:/var/log/application
      environment:
       - BEAT_NAME=app-beat
       - INDEX_NAME=appbeat
networks:
  elk:
    driver: bridge

