version: '3'

services:
    elk:
      build: "elk"
      ports:
        -  "5601:5601"
        -  "9200:9200" 
        -  "5044:5044"
      networks: 
        - elk
    # redis:
    #   image: "redis:alpine"
    #   ports:
    #     - "6379:6379"
    #   networks: 
    #     - elk
    filebeat:
      build: "filebeat"
      networks: 
        - elk
      depends_on: 
        - elk

networks: 
  elk:
    driver: bridge

  