version: '3'

services:
    es:
      image: "cobrijani/elusive:latest_es"
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - "elk"
      volumes:
        - ./elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      container_name: "elasticsearch"
    kibana:
      image: "cobrijani/elusive:latest_kibana"
      ports:
        - "5601:5601"
      networks:
        - "elk"
      volumes:
        - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
      container_name: "kibana"
    logstash:
      image: "cobrijani/elusive:latest_logstash"
      ports:
        - "5044:5044"
      networks:
        - "elk"
      volumes:
        - ./logstash/logstash.yml:/opt/logstash/config/logstash.yml
        - ./logstash/pipeline/:/etc/logstash/conf.d/
        - ./logstash/patterns/:/opt/logstash/patterns/
      container_name: "logstash"
    apachebeat:
      image: "cobrijani/elusive:latest_filebeat"
      networks:
        - elk
      volumes:
        - ./../test_logs/apache/:/var/log/apache
      environment:
        - BEAT_NAME=apache-beat
        - INDEX_NAME=apachebeat
      container_name: "apachebeat"
    firebeat:
      image: "cobrijani/elusive:latest_filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/firewall/:/var/log/firewall
      environment:
       - BEAT_NAME=fire-beat
       - INDEX_NAME=firebeat
      container_name: "firebeat"
    appbeat:
      image: "cobrijani/elusive:latest_filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/application/:/var/log/application
      environment:
       - BEAT_NAME=app-beat
       - INDEX_NAME=appbeat
      container_name: "appbeat"
    linuxbeat:
      image: "cobrijani/elusive:latest_filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/linux/:/var/log/linux
      environment:
       - BEAT_NAME=linux-beat
       - INDEX_NAME=linuxbeat
      container_name: "linuxbeat"
networks:
  elk:
    driver: bridge
