version: '3'

services:
    es:
      build: "elasticsearch"
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - "elk"
      volumes:
        - ./elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      container_name: "elasticsearch"
    kibana:
      build: "kibana"
      ports:
        - "5601:5601"
      networks:
        - "elk"
      volumes:
        - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
      container_name: "kibana"
    logstash:
      build: "logstash"
      ports:
        - "5044:5044"
      networks:
        - "elk"
      volumes:
        - ./logstash/logstash.yml:/opt/logstash/config/logstash.yml
        - ./logstash/pipeline/:/etc/logstash/conf.d/
        - ./logstash/patterns/:/opt/logstash/patterns/
      container_name: "logstash"
    apache-client-beat:
      build: "filebeat"
      networks:
        - elk
      volumes:
        - ./../test_logs/apache/:/var/log/apache
      environment:
        - BEAT_NAME=apache-beat
        - INDEX_NAME=apachebeat
      container_name: "apache-client-beat"
    firebeat:
      build: "filebeat"
      networks:
       - elk
      volumes:
       - ./../test_logs/firewall/:/var/log/firewall
      environment:
       - BEAT_NAME=fire-beat
       - INDEX_NAME=firebeat
      container_name: "firebeat"
    atmbeat:
      build: "filebeat"
      networks:
        - elk
      volumes:
        - ./../test_logs/atm/:/var/log/atm
      environment:
        - BEAT_NAME=atm-beat
        - INDEX_NAME=atmbeat
      container_name: "atmbeat"
    apache-main-beat:
      build: "filebeat"
      networks:
        - elk
      volumes:
        - ./../test_logs/apache-main/:/var/log/apache-main
      environment:
        - BEAT_NAME=apache-main-beat
        - INDEX_NAME=apachemainbeat
      container_name: "apache-main-beat"
    mongodb:
      image: "mongo:latest"
      ports:
        - "27017:27017"
      networks:
        - elk
      container_name: "mongodb"
    simulator:
      build: "simulator-service"
      networks:
        - "elk"
      ports:
        - "3000:3000"
      container_name: "simulator-service"
    # packetbeat:
    #   build: "packetbeat"
    #   cap_add: ['NET_RAW', 'NET_ADMIN']
    #   network_mode: host
    #   volumes:
    #     - ./packetbeat/packetbeat.yml:/etc/packetbeat/packetbeat.yml
    #   environment:
    #     - BEAT_NAME=packetbeat
    #     - INDEX_NAME=packetbeat
    #   container_name: "packetbeat"
    # packetbeat:
    #   image: docker.elastic.co/beats/packetbeat:5.4.1
    #   cap_add: ['NET_RAW', 'NET_ADMIN']
    #   network_mode: host
    #   volumes:
    #     - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    #     - ./packetbeat/cryptography/certs/ca/ca.pem:/usr/share/packetbeat/ca.pem
    #     - ./packetbeat/cryptography/certs/beats/beats.pem:/usr/share/packetbeat/beats.pem
    #     - ./packetbeat/cryptography/certs/beats/beats.key:/usr/share/packetbeat/beats.key
    #   environment:
    #     - BEAT_NAME=packetbeat
    #     - INDEX_NAME=packetbeat
    #   container_name: "packetbeat"
    # configure_kibana:
    #   image: docker.elastic.co/beats/metricbeat:5.4.1
    #   volumes: ['./scripts/configure-kibana.sh:/usr/local/bin/configure-kibana.sh:ro']
    #   command: ['/bin/bash', '-c', 'cat /usr/local/bin/configure-kibana.sh | tr -d "\r" | bash']
    #   environment: ['ELASTIC_VERSION=5.4.1']
    #   networks: ['elk']
    #   depends_on: ['kibana']
networks:
  elk:
    driver: bridge
